version: '3.8'

services:
  restaurant:
    build:
      context: ./restaurant
    container_name: restaurant-dev
    command: npm run start:dev
    volumes: []
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=restaurant_dev
    depends_on:
      - postgres

  restaurant-frontend:
    build:
      context: ./restaurant-frontend
    container_name: restaurant-frontend-dev
    command: npm run dev
    volumes:
      - ./restaurant-frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  postgres:
    image: postgres:16-alpine
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurant_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx-dev
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - restaurant-frontend
      - restaurant

volumes:
  pgdata_dev: